# Generated by Django 3.2.25 on 2025-01-24 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('coreobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blogapp.coreobject')),
                ('description', models.TextField()),
            ],
            bases=('blogapp.coreobject',),
        ),
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('coreobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blogapp.coreobject')),
                ('text', models.TextField()),
            ],
            bases=('blogapp.coreobject',),
        ),
    ]
